version: "3.9"

services:
  ai:
    build: .
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ~/.kaggle:/root/.kaggle
    deploy:
      resources:
        reservations:
           devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]